sudo: false
language: node_js
node_js:
- 10
git:
  submodules: false
after_success: npm run coverage
jobs:
  include:
    - stage: test
      install:
        - cd src
        - npm install  
      script:
        - cd src
        - npm test  
